- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x kubectl
- mv ./kubectl /usr/local/bin/kubectl
- wget https://storage.googleapis.com/kubernetes-helm/helm-v2.14.0-linux-amd64.tar.gz -O helm.tar.gz; tar -xzf helm.tar.gz
- chmod +x ./linux-amd64/helm
- mv ./linux-amd64/helm /usr/local/bin/helm
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image..
